defaults = [
    {"url": "https://i.imgur.com/e4jKRa4.png", "answers": ["otter"]},
    {"url": "https://i.imgur.com/P6sPJzl.jpeg", "answers": ["hond"]},
    {"url": "https://i.imgur.com/o2kotzD.jpg", "answers": ["kat", "poes"]},
    {"url": "https://i.imgur.com/mx66SBD.jpeg", "answers": ["sinaasappel"]},
    {"url": "https://i.imgur.com/V8SS4Yk.jpeg", "answers": ["banaan", "bananen"]},
    {
        "url": "https://media.newyorker.com/photos/5f2c85539a557880d973a759/2:2/w_1592,h_1592,c_limit/Buford-FrenchRice.jpg",
        "answers": ["rijst"]},
    {
        "url": "https://cdn.shopify.com/s/files/1/0336/7167/5948/products/image-of-pumpkins-vegetables-27960732713004_600x600.jpg?v=1618238328",
        "answers": ["pompoen"]},
    {
        "url": "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/07/what_to_know_apples_green_red_1296x728_header-1024x575.jpg",
        "answers": ["appel"]},
    {"url": "https://pngimg.com/uploads/sword/sword_PNG5525.png", "answers": ["zwaard"]},
    {"url": "https://www.spacex.com/static/images/content/fh_performance.jpg", "answers": ["raket", "falcon heavy", "spacex"]},
    {
        "url": "https://tesla-cdn.thron.com/delivery/public/image/tesla/3863f3e5-546a-4b22-bcbc-1f8ee0479744/bvlatuR/std/1200x628/MX-Social",
        "answers": ["tesla", "auto"]},
    {
        "url": "https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_21/2870431/190524-classic-american-cheeseburger-ew-207p.jpg",
        "answers": ["burger", "hamburger"]},
    {"url": "https://images.immediate.co.uk/production/volatile/sites/30/2021/03/French-fries-b9e3e0c.jpg",
     "answers": ["friet", "franse friet", "patat"]},
    {"url": "https://qvc.scene7.com/is/image/QVC/h/18/h227018.001", "answers": ["kleed", "mat"]},
    {"url": "https://productimages.mybobs.com/20035205017/20035205017_gallery_01_wide.jpg", "answers": ["bureau"]},
    {"url": "https://images.techopedia.com/images/uploads/television.jpg", "answers": ["tv", "televisie"]},
    {"url": "https://www.emergenthealth.org/wp-content/uploads/2020/03/082019_EHP_MRM1499.jpg",
     "answers": ["ambulance"]},
    {"url": "https://electrek.co/wp-content/uploads/sites/3/2022/11/Lion-electric-US-factory-1.jpeg",
     "answers": ["schoolbus", "school bus"]},
    {"url": "https://m.media-amazon.com/images/I/71ARSWzCZBL.jpg", "answers": ["spatel"]},
    {"url": "https://wherethewindsblow.com/wp-content/uploads/2015/07/JUMBO-Six-sided-white-dice.jpg",
     "answers": ["dobbelstenen", "dobbelsteen"]},
    {
        "url": "https://assets.bonappetit.com/photos/58dbf6c8a6614f6f50816994/4:3/w_2591,h_1943,c_limit/20170323%20MOB6231_FINAL_crop.jpg",
        "answers": ["aardbei"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Cow_female_black_white.jpg", "answers": ["koe"]},
    {
        "url": "https://cb2.scene7.com/is/image/CB2/KMPolarTableLampSHS21/$web_pdp_main_carousel_xs$/210210135642/polar-table-lamp.jpg",
        "answers": ["lamp"]},
    {"url": "https://niteize.com/media/catalog/product/T/1/T11RA-01-R8_F_0054b_SQRGB_1.jpg", "answers": ["zaklantaarn", "zaklamp"]},
    {"url": "https://cdn.mos.cms.futurecdn.net/iC7HBvohbJqExqvbKcV3pP.jpg", "answers": ["aardappel", "aardappels"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Candy-Cane-Classic_thumbnail.png",
     "answers": ["candycane", "zuurstok"]},
    {"url": "https://www.familyhandyman.com/wp-content/uploads/2019/03/shutterstock_208428820-Chimney.jpg",
     "answers": ["schoorsteen"]},
    {"url": "https://www.overlandexpo.com/wp-content/uploads/2021/05/campfire-1493151033GIm-1.jpg",
     "answers": ["kampvuur", "kamp vuur"]},
    {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Chenille_de_Grand_porte_queue_%28macaon%29.jpg/800px-Chenille_de_Grand_porte_queue_%28macaon%29.jpg",
        "answers": ["rups"]},
    {"url": "https://assets.bonappetit.com/photos/5c62e4a3e81bbf522a9579ce/5:4/w_2815,h_2252,c_limit/milk-bread.jpg",
     "answers": ["brood"]},
    {"url": "https://images.eatthismuch.com/img/814308_tiffanyh1_0ec52be5-fafc-4438-8706-530025a90b1d.jpg",
     "answers": ["toast"]},
    {"url": "https://cdn.britannica.com/64/143464-050-B0EC6714/Eggplant.jpg", "answers": ["aubergine", "aubergines"]},
    {"url": "https://cdn.britannica.com/65/12565-050-B102B3A8/crown-Denmark-helmet-form-enamel-gold-stones-1670.jpg",
     "answers": ["kroon"]},
    {"url": "https://i.insider.com/61f83cd8415c3f0018d3c5a0?width=721&format=jpeg",
     "answers": ["jet", "f15", "f-15", "f-15ex", "vliegtuig"]},
    {"url": "https://upload.wikimedia.org/wikipedia/en/a/a9/MarioNSMBUDeluxe.png", "answers": ["mario"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg",
     "answers": ["boom"]},
    {"url": "https://m.media-amazon.com/images/I/61Z9avu0YeL.jpg", "answers": ["slot", "masterlock", "master lock"]},
    {"url": "https://www.tastingtable.com/img/gallery/coffee-brands-ranked-from-worst-to-best/l-intro-1645231221.jpg",
     "answers": ["koffie"]},
    {"url": "https://ychef.files.bbci.co.uk/976x549/p0c2qddy.jpg", "answers": ["muis"]},
    {
        "url": "https://www.toureiffel.paris/sites/default/files/actualite/image_principale/vue_depuisjardins_webbanner_3.jpg",
        "answers": ["eiffel toren", "eiffeltoren"]},
    {
        "url": "https://mtcopeland.com/wp-content/uploads/2021/03/Pe1nyluQTqwGgq4J7tqF_shutterstock_1409057786_openended.jpg",
        "answers": ["steeksleutel"]},
    {
        "url": "https://www.harborfreight.com/media/catalog/product/cache/9fc4a8332f9638515cd199dd0f9238da/5/6/56508_W3.jpg",
        "answers": ["schroevendraaier"]},
    {
        "url": "https://images.squarespace-cdn.com/content/57fd5aa69f745699d45f362d/1608759631347-N3CDZS7OJVM1EQPDJZEZ/?format=1500w&content-type=image%2Fjpeg",
        "answers": ["bout"]},
    {
        "url": "https://i5.walmartimages.com/asr/cadb77b5-c111-43ea-8d49-920ad49448c1.658ec8185ae011eb9113fcaa3ebdd220.jpeg",
        "answers": ["moeren", "moer"]},
    {
        "url": "https://i0.wp.com/post.healthline.com/wp-content/uploads/2019/11/chestnut-nut-nuts-peanuts-pistachio-cashew-1296x728-header-1296x728.jpg",
        "answers": ["noot", "noten"]},
    {"url": "https://images.immediate.co.uk/production/volatile/sites/30/2017/01/avocado-45bccf2-scaled.jpg",
     "answers": ["avocado"]},
    {"url": "https://assets.bonappetit.com/photos/60ef61f34d6cfb72ea6baeec/master/pass/Sweet-Sour-Cherries.jpg",
     "answers": ["kers", "kersen"]},
    {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/1200px-Giraffe_Mikumi_National_Park.jpg",
        "answers": ["giraffe"]},
    {"url": "https://www.humanesociety.org/sites/default/files/styles/1240x698/public/2022-03/hippo-560952.jpg",
     "answers": ["nijlpaard"]},
    {"url": "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg",
     "answers": ["hond"]},
    {
        "url": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2022-08/220805-border-collie-play-mn-1100-82d2f1.jpg",
        "answers": ["hond"]},
    {"url": "https://static01.nyt.com/images/2022/05/10/science/28DOGS-BEHAVIOR1/28DOGS-BEHAVIOR1-mobileMasterAt3x.jpg",
     "answers": ["hond"]},
    {"url": "https://i.natgeofe.com/k/3152d4f7-99e0-4875-bac2-f3f4366e78ed/yikes-vampirebat_3x4.png",
     "answers": ["vleermuis"]},
    {"url": "https://upload.wikimedia.org/wikipedia/en/1/1e/Baseball_%28crop%29.jpg", "answers": ["honkbal"]},
    {
        "url": "https://cdn1.polaris.com/globalassets/indian/2022/model/chief-cgi-updates/vehicle-cards/chief-bobber-dark-horse-sagebrush-smoke.png",
        "answers": ["motor", "motorfiets"]},
    {"url": "https://d29sx7s964xey6.cloudfront.net/52950879-ee2e-4b32-9cdc-3bc97a096004_SRS_Asphalt.136.1.png",
     "answers": ["motor", "motorfiets"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/4/41/Left_side_of_Flying_Pigeon.jpg",
     "answers": ["fiets"]},
    {"url": "https://m.media-amazon.com/images/I/81TGQaXnlEL._AC_SL1500_.jpg", "answers": ["clown"]},
    {
        "url": "https://www.ikea.com/us/en/images/products/dragon-salad-dessert-fork-stainless-steel__0711373_pe728216_s5.jpg",
        "answers": ["vork", "vorken"]},
    {"url": "https://images-cdn.ubuy.co.id/5B0NIMO-3-5.jpg", "answers": ["radio"]},
    {"url": "https://m.media-amazon.com/images/I/71dNlmxB6EL.jpg",
     "answers": ["walkie talkie", "walky talky", "walkietalkie"]},
    {"url": "https://a-z-animals.com/media/2020/01/Snake-Blue-viper.jpg", "answers": ["slang"]},
    {"url": "https://media.cnn.com/api/v1/images/stellar/prod/220320181933-01-rare-snake-alabama-handout.jpg",
     "answers": ["slang"]},
    {
        "url": "https://cdn.shopify.com/s/files/1/0755/3707/products/shark-helmets-street-drak-blank-matte-green-HE3306DGMA-front-left_1024x1024.jpg",
        "answers": ["helm"]},
    {"url": "https://www.polyjohn.com/media/pjn3_row.jpg", "answers": ["portopotty", "porto potty", "portable toilet", "dixi"]},
    {"url": "https://m.media-amazon.com/images/I/41WJMrUZhjL._AC_SY1000_.jpg", "answers": ["bijl", "axe"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Accetta.jpg/1200px-Accetta.jpg",
     "answers": ["axe"]},
    {"url": "https://cdn.shopify.com/s/files/1/0594/4937/6920/files/light-saber-hero-desktop-1_1200x.jpg",
     "answers": ["lichtzwaard", "licht zwaard"]},
    {"url": "https://blogs.windows.com/wp-content/uploads/2017/06/8c2133bc59b7dea5a6fb40725fe9e4dc.jpg",
     "answers": ["windows"]},
    {"url": "https://www.redhat.com/cms/managed-files/tux-327x360.png", "answers": ["linux", "pinguin"]},
    {
        "url": "https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/wp-content/uploads/2021/04/double-hung-window.jpeg-1.jpg",
        "answers": ["raam"]},
    {
        "url": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg",
        "answers": ["berg"]},
    {"url": "https://i.natgeofe.com/k/830b5d15-92db-429f-a80a-cc89b5700af5/mt-everest.jpg", "answers": ["berg"]},
    {"url": "https://cdn.britannica.com/08/100608-050-684264CB/Saguaro-cactus-Arizona.jpg",
     "answers": ["cactus", "cacti"]},
    {"url": "https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg",
     "answers": ["zonnebloem", "bloem"]},
    {
        "url": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-tulips-blooming-in-field-royalty-free-image-1584131603.jpg",
        "answers": ["bloemen", "bloem"]},
    {"url": "https://cdn.mos.cms.futurecdn.net/snbrHBRigvvzjxNGuUtcck.jpg", "answers": ["maan", "de maan"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/c/cb/The_Blue_Marble_%28remastered%29.jpg",
     "answers": ["aarde", "de aarde"]},
    {"url": "https://i.natgeofe.com/k/7c7e4173-5ad3-4ef7-8252-354de21430db/jupiter_3x4.jpg", "answers": ["jupiter"]},
    {"url": "https://solarsystem.nasa.gov/system/stellar_items/image_files/38_saturn_1600x900.jpg",
     "answers": ["saturnus"]},
    {"url": "https://m.media-amazon.com/images/I/31uQV2huSzL._AC_.jpg", "answers": ["koptelefoon"]},
    {
        "url": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1623788898-cheap-cell-phone-gallery-4-1623788892.jpg",
        "answers": ["smartphone", "telefoon", "phone"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Telefon_BW_2012-02-18_13-44-32.JPG",
     "answers": ["telefoon", "phone"]},
    {
        "url": "https://www.bhphotovideo.com/images/images2500x2500/mg_electronics_pgm_15pd_15_watt_ultra_lightweight_1566745.jpg",
        "answers": ["megafoon", "mega foon"]},
    {"url": "https://m.media-amazon.com/images/I/31zQcpzk-BL.jpg",
     "answers": ["vuilnisbak", "prullenbak", "vuilnisemmer"]},
    {"url": "https://www.kbb.com/wp-content/uploads/2021/07/2021-gmc-sierra-at4-hd-front-right.jpg",
     "answers": ["truck", "vrachtwagen"]},
    {
        "url": "https://i.natgeofe.com/n/2f169ccb-e943-4772-8bd1-c92e79db64ab/gsfc_20171208_archive_e000922_orig_square.jpg",
        "answers": ["zon", "ster"]},
    {"url": "https://cdn.britannica.com/05/94905-050-1830515C/Whirlpool-Galaxy-NGC-5195-Sc.jpg", "answers": ["melkweg", "hemel", "sterrenstelsel", "sterren"]},
    {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/NGC_4414_%28NASA-med%29.jpg/1200px-NGC_4414_%28NASA-med%29.jpg",
        "answers": ["melkweg", "hemel", "sterrenstelsel", "sterren"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Calculator.kodabar.jpg", "answers": ["calculator", "rekenmachine"]},
    {
        "url": "https://images2.minutemediacdn.com/image/upload/c_fill,w_1440,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/24832-istock-698876630-9699ecd2ca21cc77daaab9567e646205.jpg",
        "answers": ["potlood", "potloden"]},
    {"url": "https://logos-world.net/wp-content/uploads/2020/12/Discord-Logo.png", "answers": ["discord"]},
    {
        "url": "https://imgs.michaels.com/MAM/assets/1/726D45CA1C364650A39CD1B336F03305/img/0B720CDD518C480290463DBEE9FA9EB5/10405225_1.jpg",
        "answers": ["schaar", "scharen"]},
    {
        "url": "https://nationalzoo.si.edu/sites/default/files/styles/1400_scale/public/animals/exhibit/africanlion-005.jpg",
        "answers": ["leeuw"]},
    {
        "url": "https://images.pexels.com/photos/62627/niagara-cases-water-waterfall-62627.jpeg?cs=srgb&dl=pexels-pixabay-62627.jpg",
        "answers": ["waterval"]},
    {
        "url": "https://media.cntraveler.com/photos/57211a94fe5fd76f60bc2760/master/w_2048,h_1536,c_limit/deserts-gobi-cr-GettyImages-582205681.jpg",
        "answers": ["sahara", "woestijn"]},
    {"url": "https://www.allaboutbirds.org/news/wp-content/uploads/2020/07/STanager-Shapiro-ML.jpg",
     "answers": ["vogel"]},
    {
        "url": "https://www.theglobeandmail.com/resizer/uTDQFXw9l38qb37gyVWJ5ueQwRA=/arc-anglerfish-tgam-prod-tgam/public/KMJBINCJBZBWVFK66LDFCCQBNY.jpg",
        "answers": ["uil", "vogel"]},
    {
        "url": "https://assets.weimgs.com/weimgs/ab/images/wcm/products/202226/0293/mid-century-leather-show-wood-chair-1-c.jpg",
        "answers": ["stoel"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/a/a1/JM_marbles_01.jpg", "answers": ["knikker", "knikkers"]},
]
